name: Mise à jour des données Loto

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code du dépôt EN UTILISANT LE PAT
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # === MODIFICATION 1 : Le token est mis ICI ===
          token: ${{ secrets.ACTIONS_PAT }}

      # 2. Scrape la page FDJ, télécharge et dézippe le fichier
      - name: Download and Unzip Loto Data
        run: |
          HISTORY_PAGE_URL="https://www.fdj.fr/jeux-de-tirage/loto/historique"
          DOWNLOAD_URL=$(curl -s $HISTORY_PAGE_URL | grep -o 'https://www.sto.api.fdj.fr/anonymous/service-draw-info/v3/documentations/[^"]*' | head -n 1)
          if [ -z "$DOWNLOAD_URL" ]; then
            echo "Erreur: Impossible de trouver le lien de téléchargement."
            exit 1
          fi
          echo "Lien trouvé : $DOWNLOAD_URL"
          curl -L -o loto_new.zip "$DOWNLOAD_URL"
          unzip -o loto_new.zip
          echo "Fichier dézippé avec succès."

      # 3. Met en place l'environnement R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::readr
            any::dplyr
            any::lubridate
          cache: true

      # 4. Exécute le script R pour combiner les données
      - name: Run R script
        run: Rscript combine_script.R

      # 5. Sauvegarde les changements dans le dépôt si le fichier a été modifié
      - name: Commit and push if changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📊 Chore: Mise à jour des données Loto"
          file_pattern: 'loto_combined.csv'
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
